### ISSUE TITLE
PA Review: Courses

### ISSUE THREAD

**Issue by cjthom03** [cjthom03/UdemyClone#14]
* **Backend**: 
  - [x] DB migrations - `courses`, `ratings`
  - [x] Models - `course`, `rating`
  - [x] Seed - create 10 dummy courses, each with 25-50 ratings
  - [x] Routes - namespace api `courses, only [:index, :show]`
  - [x] Controllers - `api/courses` controlling `#index` and `#show`
  - [x] Views - JSON `index`,`show`

**Note**: For now, index can return all courses, but at some point, the number will need to be limited (10-20) and a different set of courses should be returned for each ajax call for the home page.

***

* **Redux Loop**: 
  - [x] Ajax - `fetchCourses`, `fetchSingleCourse`
  - [x] Actions - `receiveCourses`, `receiveSingleCourse`, 
  - [x] Actions for loading
  - [x] Thunk Actions - `fetchCourses`, `fetchSingleCourse`,
  - [x] Reducers - `entities` + `courses`
  - [x] Reducers - `ui` + `loading`

**Notes**: 
  * `courses` slice of state will not yet include `lesson_count` or `total_lesson_duration`
  * May need to include a selector for `courses` to get an array of the courses needed for the index page

***

* **Presentational Components and Containers**
  - [x] Home page banner(s)
  - [x] `CoursesContainer` + `CoursesIndex` + `CoursesIndexItem`
  - [x] `CourseBannerContainer` + `CourseBanner`
  - [x] UI Loading CSS Spinner - for home page

***

* **UX / UI**
  - [x] Styling
  - [x] Smooth, bug-free navigation
  - [x] Adequate and appropriate seeds - dummy information for now

**Comment by cjthom03** [comment]
Completed MVP 3 - Courses. Note that my seed data is all generic at the moment, as I plan to see the database all at once before I do my search MVP.

Take a look here - [https://udemy-clone.herokuapp.com/#/courses/2](https://udemy-clone.herokuapp.com/#/courses/2)

**Comment by eshoule** [comment]
Great job! Closing this issue.
