### ISSUE TITLE
PA Review: Lessons

### ISSUE THREAD

**Issue by cjthom03** [cjthom03/UdemyClone#16]
* **Backend**: 
  - [x] DB migrations - `lessons`
  - [x] Models - `lesson` => association with `course`
  - [x] Models - `courses` => add method to get total course duration
  - [x] Seed - create 5-10 dummy lessons for each course
  - [x] Routes - NONE
  - [x] Controllers - NO new controllers
  - [x] Controllers - modify `courses#show` to include `lessons` in DB query
  - [x] Views - modify the JSON `show` rendered by the `course` controller to 
     1) include lesson data
     2) include `lesson_count` and `total_lesson_duration` in the `courses` slice of state

**Notes**
  * No new api routes needed. Lesson `GET` requests will be made directly to YouTube from the front end lesson component.
  * No new routes means no new controllers.
***

* **Redux Loop**: 
  - [x] Ajax, my backend - NONE - use `fetchSingleCourse`
  - [x] Ajax, to YouTube (embedded iframe)
  - [x] Actions - NONE - use `receiveSingleCourse`, 
  - [x] Thunk Actions - NONE - use `fetchSingleCourse`
  - [x] Reducers - `entities` + `lessons`
  - [x] Reducers - `lessons` selector to get an array of lessons
  - [x] Reducers - `lessons` selector to get an array of lesson order numbers
  - [x] Reducers - 'ui' + 'sidebar'

**Notes**: 
  * `courses` slice of state will not yet include `lesson_count` or `total_lesson_duration`
  * May need to include a selector for `courses` to get an array of the courses needed for the index page

***

* **Presentational Components and Containers**
  - [x] Routes - `/#/courses/:courseId/lesson/:lessonId`
  - [x] `LessonsIndex` + `LessonsIndexItem`
  - [x] `ActiveLessonContainer` + `ActiveLesson` + YouTube `<iframe>`
  - [x] Protected route - cannot access lessons if not logged in

** Notes **
  * Protected route will need to be updated in next MVP to not allow for subscriptions or lessons if not logged it, and not allow for lessons if not subscribed.
  * A `LessonsContainer` was not needed for the course show page, it was removed from the component hierarchy as well

***

* **UX / UI**
  - [x] Styling
  - [x] Smooth, bug-free navigation
  - [x] Adequate and appropriate seeds

**Comment by cjthom03** [comment]
MVP #4 complete - check it out here: [https://udemy-clone.herokuapp.com/#/courses/46](https://udemy-clone.herokuapp.com/#/courses/46)

Note: If you run into issues with videos playing, try turning off your adblocker. This can apparently be an issue with YouTube's iframe. Let me know if you have issues so I can add a disclaimer if the user has an adblocker running.

**Comment by eshoule** [comment]
Great job!
