### ISSUE TITLE
PA Review: Subscribe to Courses

### ISSUE THREAD

**Issue by cjthom03** [cjthom03/UdemyClone#17]
* **Backend**: 
  - [x] DB migrations - `subscriptions`
  - [x] Models - `subscription` => associations with `course` and `user`
  - [x] Seed - give demo user 3 course subscriptions
  - [x] Routes - `api/subscriptions` 
  - [x] Controllers - `subscriptions` only `[create, index]`
  - [x] Views - `index` for `api/subscriptions` to return all subscriptions
  - [x] Views - `show` for `api/subscriptions` to return a single subscription after created

**Notes**
  * Only post requests will be made to `subscriptions`. Users cannot un-subscribe from courses.

***

* **Redux Loop**: 
  - [x] Ajax - `fetchSubscriptions` and `postSubscription`
  - [x] Actions - `receiveSubscriptions` and `receiveSingleSubscription`
  - [x] Thunk Actions - `fetchSubscriptions` and `postSubscription`
  - [x] Reducers - `entities` + `subscriptions`

***

* **Presentational Components and Containers**
  - [x] Routes - `/#/my-courses`
  - [x] Components - `MyCoursesContainer` + reuse `CourseIndex` and `CourseIndexItem`
  - [x] Components - edit `CourseShow` to have a working subscription button
  - [x] Protected route - cannot access `/my-courses` unless logged in
  - [x] Subscription route - cannot access `activeLesson` unless logged in AND subscribed

***

* **UX / UI**
  - [x] Styling
  - [x] Smooth, bug-free navigation
  - [x] Adequate and appropriate seeds

**Comment by cjthom03** [comment]
Check it out - https://udemy-clone.herokuapp.com/#/courses/7

**Comment by eshoule** [comment]
Looks great!
