### ISSUE TITLE
PA Review: Search

### ISSUE THREAD

**Issue by cjthom03** [cjthom03/UdemyClone#19]
* **Backend**: 
  - [x] DB migrations - NONE
  - [x] Models - NONE
  - [x] Seed - No new seed data needed at this time
  - [x] Routes - `api/search` 
  - [x] Controllers - `search` only `[index]`
  - [x] Views - `index` for `api/search` to return all search results, using the `api/courses/_course` partial
  - [x] Views - `dropdown` for `api/search` to return up to 10 search results

**Notes**
  * `search#index` will accept `LIMIT` and `query` parameters as well as a url path, and will either return limited results for the dropdown container (which will modify the search results slice of state) or will return all the results (modifying the courses slice of state)

***

* **Redux Loop**: 
  - [x] Ajax - `fetchSearchResults`
  - [x] Actions - `receiveAllSearchResults`, `receiveDropdownSearchResults` and `clearSearchResults`
  - [x] Thunk Actions - `fetchAllSearchResults` and `fetchDropdownSearchResults`
  - [x] Reducers - `entities` + `searchResults`
  - [x] Reducers - modify `courses` reducer to handle `receiveAllSearchResults`

**Notes**
  * `clearSearchResults` will be dispatched on `componentWillUnmount()` for the search index 
  * The `searchResults` slice of state will only be used for dropdown search results, otherwise the courses slice of state will be used for all search results

***

* **Presentational Components and Containers**
  - [x] Routes - `/#/search/?q=search+terms+go+here`
  - [x] Components - `SearchResultsContainer` + `SearchResultsIndex` + `SearchResultsIndexItem`
  - [x] Components - `SearchBar` form
  - [x] Components - `SearchContainer` + `SearchIndex` + `SearchIndexItem`
  - [x] Reroute -  `/#/search` without a query string re-directs to `/`

***

* **UX / UI**
  - [x] Styling
  - [x] Smooth, bug-free navigation
  - [x] Adequate and appropriate seeds

**Comment by cjthom03** [comment]
MVP Complete, check it out - [https://udemy-clone.herokuapp.com/#/](https://udemy-clone.herokuapp.com/#/)

**Comment by cjthom03** [comment]
I fixed the dropdown search to allow for keydown actions for down & up arrows - and pushed to heroku. It is now ready for review [https://udemy-clone.herokuapp.com/#/](https://udemy-clone.herokuapp.com/#/)

**Comment by eshoule** [comment]
Awesome! Closed!
