### ISSUE TITLE
PA Review: Completions

### ISSUE THREAD

**Issue by cjthom03** [cjthom03/UdemyClone#20]
* **Backend**: 
  - [x] DB migrations - `completions`
  - [x] Models - `completion`, associations with `user` and `lesson`
  - [x] Seed - demo user can start with a 1-3 completions per subscribed course
  - [x] Routes - `api/completions` 
  - [x] Controllers - `api/completions` only `[:create, :destroy]`
  - [x] Views - `show` for `api/completions` to return 1 completions (the recently created or deleted)
  - [x] Views - modify `show` for `api/courses` to include all user completions for that course

***

* **Redux Loop**: 
  - [x] Ajax - `postCompletion` and `destroyCompletion`
  - [x] Actions - `receiveCompletion` and `removeCompletion`
  - [x] Thunk Actions - `postCompletion` and `destroyCompletion`
  - [x] Reducers - `entities` + `completions`
  - [x] Reducers - `completions_reducer` will also need to handle `receiveSingleCourse` action
  - [x] Reducers - `nextLesson` selector to identify the next lesson the user has not yet completed

***

* **Presentational Components and Containers**
  - [x] Routes - NONE - no new routes needed for completions
  - [x] Components - `CourseShow` header to include count of lessons completed / progress bar
  - [x] Components - `lessonIndexItem` to show if completed AND allow for registering manual completions
  - [x] Components - `CourseShow` button to change to play the next incomplete lesson
  - [x] Components - `ActiveLesson` - refactor YouTube Iframe to handle completion event 
  - [x] Reroutes -  No new routing required

***

* **UX / UI**
  - [x] Styling
  - [x] Smooth, bug-free navigation
  - [x] Adequate and appropriate seeds

**Comment by cjthom03** [comment]
Complete - check it out [https://udemy-clone.herokuapp.com/#/my-courses](https://udemy-clone.herokuapp.com/#/my-courses)

Also, I fixed the problems with the infinite css spinners for search/ and courses/ paths

**Comment by eshoule** [comment]
Amazing! I'm so proud.
