### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by cjthom03** [cjthom03/UdemyClone#9]
* Backend: 
  - [x] DB migrations - `users`
  - [x] Models - `user`
  - [x] Routes - `static_pages#root`, namespace api `users` and `session`
  - [x] Controllers - `StaticPages`, `api/users`, `api/sessions`
  - [x] Views - `static_pages`, JSON `show`
* Redux Loop: 
  - [x] Ajax - `signup`, `login`, `logout`
  - [x] Actions - `signup`, `login`, `logout`
  - [x] Reducers - `root`, `entities` + `users`, `session`, `errors` + `session_errors`
  - [x] Store - Initial setup; Configure with `thunk` and `logger` middleware
* Presentational Components and Containers
  - [x] App & Root components
  - [x] NavBar + SessionButtons (placeholder input text for search bar)
  - [x] Session Modal + SessionFormContainer + SessionForm
  - [x] Footer
* UX / UI
  - [x] Styling
  - [x] Smooth, bug-free navigation
  - [x] Adequate and appropriate seeds

**Comment by cjthom03** [comment]
Completed user auth and pushed to Heroku [https://udemy-clone.herokuapp.com/](https://udemy-clone.herokuapp.com/)

**Comment by eshoule** [comment]
Charlie, it looks great! Just make this one change, and I will close the issue. 
- [ ] Going to a random route /#/oweiniouewbrviuwebv should redirect to either /, /login, or /signup. Your page doesn't change, but the frontend route doesn't redirect.

**Comment by cjthom03** [comment]
Complete - I added a switch statement with a final <Redirect to='/' /> condition and pushed to Heroku. Go ahead and take a look [https://udemy-clone.herokuapp.com/#/](https://udemy-clone.herokuapp.com/#/)

**Comment by eshoule** [comment]
Awesome!
